#!/usr/bin/env bash

index=0
for reg in k8s.gcr.io registry-1.docker.io quay.io gcr.io
do
        docker stop ${reg} || true
        docker rm ${reg} || true
	regdir="/registry/${reg}"
	docker run -d -p $(( 5000 + ${index} )):5000 \
		-e REGISTRY_LOG_LEVEL=debug \
		-e REGISTRY_PROXY_REMOTEURL=https://${reg} \
		-v "${regdir}:/var/lib/registry" \
		--restart always \
		--name ${reg} registry:2
	index=$(( $index + 1))
done

# docker run -d -p 5000:5000 \
#     -e REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io \
#     --restart always \
#     --name registry-docker.io registry:2
# 
# docker run -d -p 5001:5000 \
#     -e REGISTRY_PROXY_REMOTEURL=https://k8s.gcr.io \
#     --restart always \
#     --name registry-k8s.gcr.io registry:2
# 
# docker run -d -p 5002:5000 \
#     -e REGISTRY_PROXY_REMOTEURL=https://quay.io \
#     --restart always \
#     --name registry-quay.io registry:2.5
# 
# docker run -d -p 5003:5000 \
#     -e REGISTRY_PROXY_REMOTEURL=https://gcr.io \
#     --restart always \
#     --name registry-gcr.io registry:2
