#!/usr/bin/env bash
#mount -t vboxsf var_vm-shared /vagrant/
mkdir -p /home/vagrant/shared/cache
#kubeadm config images pull
docker images --format '{{.ID}} {{.Repository}} {{.Tag}}' | {
	while read b a c
	do 
		echo "$b..${a##*/}-${c}.tar"
		docker save ${a} -o /home/vagrant/shared/cache/k8s-${a##*/}-${c}.tar
	done
}
