#!/usr/bin/env bash

kubeadm init --apiserver-advertise-address=$(hostname -i) \
	--control-plane-endpoint=loadbalancer:6443 \
	--upload-certs --pod-network-cidr=10.244.0.0/16

       mkdir -p $HOME/.kube
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config

	kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
#kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
